# This configuration requires 4 GPUs with 32GB memory
batch_type: numel
#batch_bins: 20000000
batch_bins: 1000000
accum_grad: 4
max_epoch: 60
patience: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
freeze_frontend: false

encoder: linear
encoder_conf:
    output_size: 2048
    num_layers: 2
    factor: false
    residual: false
    dropout: 0.1

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    use_vq_losses: true
    commitment_weight: 0.25
    codebook_weight: 1.0

optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
log_interval: 100
seed: 2022

frontend: codec
frontend_conf:
   n_quantizers: 12
   fs: 16000
   normalize_codes: false
   preprocess_signal: true
#freeze_param: ["frontend"]