# Trained with Tesla V100 (32GB) x 4 GPUs. It takes about 3.5 days.
encoder: linear
encoder_conf:
    output_size: 2048
    num_layers: 4
    factor: false
    residual: false
    dropout: 0.1

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

frontend: codec
frontend_conf:
   n_quantizers: 12
   fs: 16000
   normalize_codes: false
   preprocess_signal: true

freeze_frontend: true

use_amp: true
num_workers: 4
batch_type: numel
batch_bins: 35000000
accum_grad: 4
max_epoch: 50
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.0025
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 40000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10
